<?php

include_once($path_to_root . "/includes/banking.inc");

include_once($path_to_root . "/gl/includes/db/gl_db_trans.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_bank_trans.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_banking.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_bank_accounts.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_currencies.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_rates.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_accounts.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_account_types.inc");
include_once($path_to_root . "/gl/includes/db/gl_db_bank_trans_types.inc");

//--------------------------------------------------------------------------------


						

?>