<?php

include_once($path_to_root . "/includes/date_functions.inc");

include_once($path_to_root . "/includes/ui.inc");

include_once($path_to_root . "/purchasing/includes/ui/invoice_ui.inc");
include_once($path_to_root . "/purchasing/includes/ui/po_ui.inc");
include_once($path_to_root . "/purchasing/includes/ui/grn_ui.inc");




//--------------------------------------------------------------------------------------


?>